const conf = {
	BACKEND_URL: import.meta.env.VITE_APP_BACKEND_URL,
	CLOUDINARY_URL: import.meta.env.VITE_APP_CLOUDINARY_URL,
	VIDEO_UPLOAD_PRESET: import.meta.env.VITE_APP_VIDEO_UPLOAD_PRESET,
	THUMBNAIL_UPLOAD_PRESET: import.meta.env.VITE_APP_THUMBNAIL_UPLOAD_PRESET,
	AVATAR_UPLOAD_PRESET: import.meta.env.VITE_APP_AVATAR_UPLOAD_PRESET,
	COVERIMAGE_UPLOAD_PRESET: import.meta.env.VITE_APP_COVERIMAGE_UPLOAD_PRESET,
	OTHER_UPLOAD_PRESET: import.meta.env.VITE_APP_OTHER_UPLOAD_PRESET,
};

export default conf;
